### ISSUE TITLE
52.25.82.61:3000 is not responding.

### ISSUE THREAD

**Issue by Arcrammer** [bofuuchicago/final#1]
Hey! I'm in DPWP and I was looking around to see what the final project is like.

Your server is currently down though and this is the only way I know how to contact you...

<img width="545" alt="screen shot 2015-08-23 at 17 42 46" src="https://cloud.githubusercontent.com/assets/8358956/9430312/628d006c-49be-11e5-8ef5-b18696d75afe.png">

**Comment by bofuuchicago** [comment]
Hi Arcrammer,
I'm planning to change this repository into Cloud9 and the original one in EC2 is no longer used.
This project is still under construction, some of the functions are not currently available. Can you tell me why you wanna view this project and then I can decide whether to start the server for you

Bo

**Comment by Arcrammer** [comment]
I just wanted to know what it's like to work on the final project. Like I said earlier I'm in DPWP in the same degree program.

**Comment by bofuuchicago** [comment]
its https://final-bofuuchicago.c9.io/

**Comment by Arcrammer** [comment]
Thanks! I can't login..?

**Comment by bofuuchicago** [comment]
Please use "bof@uchicago.edumailto:bof@uchicago.edu" as username and “1234” as password.

Bo

On Aug 24, 2015, at 9:14 AM, Alexander Rhett Crammer <notifications@github.com<mailto:notifications@github.com>> wrote:

Thanks! I can't login..?

**Comment by Arcrammer** [comment]
Thanks!
